server:
  port: 8081

spring:
  application:
    name: customer-service
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.orderfulfillment.customerservice: DEBUG
    org.springframework.web: DEBUG