spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testorderdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false

# Mock external services for testing
external-services:
  customer-service:
    base-url: http://localhost:8081
  payment-service:
    base-url: http://localhost:8082

logging:
  level:
    com.orderfulfillment.orderservice: WARN